name: Bimonthly Release

on:
  schedule:
    - cron: '0 0 1 */2 *'  # Every 2 months on the 1st at midnight UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from latest successful Build run
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-ot-nrf528xx.yml                
          workflow_conclusion: success
          name: ot-nrf528xx-binaries
          branch: main
          path: downloaded

      - name: List downloaded files
        run: ls -lh downloaded

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Create GitHub release with .bin files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ steps.date.outputs.date }}"
          name: "Bimonthly Release - ${{ steps.date.outputs.date }}"
          body: |
            Automatically published release of OpenThread firmware for nRF528xx.
          files: downloaded/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
